// application/client/web/templateaccouting/src/app/loginsscreen/loginsscreen.component.ts
import { Component, OnInit } from '@angular/core';
import { LoginsscreenService } from './loginsscreen.service';

@Component({
  selector: 'app-loginsscreen',
  templateUrl: './loginsscreen.component.html',
  styleUrls: ['./loginsscreen.component.scss'],
})

export class LoginsscreenComponent implements OnInit {
    public adds:any = {
        created_date_at: '',
        created_by: '',
        last_modified_by: '',
        last_modified_date_at: '',
        name: '',
    }

    constructor (
        private loginsscreenService: LoginsscreenService,
    ) { }

    ngOnInit() {
        this.adds.created_by = sessionStorage.getItem('email') || ''; 
    }
}
<h2 class="screen-align">Loginsscreen</h2>
<div id="template-isvn" class="gjs-row">
    <div id="template-iwqv" class="gjs-cell">
        <div id="template-ix5t6" class="gjs-row">
            <div id="template-ix4oh" class="gjs-cell">
                <img id="template-iij6" src="https://grapesjs-images.s3.amazonaws.com/grapesjsimages/SvgjsG1008.png"
                </div>
            </div>
            <div id="template-ictg" class="">The GST Council Has Made E-Invoicing Mandatory for Businesses with a Turnover
                Of ₹10Cr. Or More From October 2023. 10Decoders Books Is Here To Help.</div>
            <div
            id="template-ihzr" class="gjs-row">
                <div id="template-ijc9" class="gjs-cell">
                    <img id="template-i5e9" src="https://grapesjs-images.s3.amazonaws.com/grapesjsimages/Mask%20Group%2029.png"
                    </div>
                </div>
                <div id="template-ihxdj" class="gjs-row">
                    <div id="template-iomak" class="gjs-cell">
                        <div id="template-iz9hl" class="">Reach Out To Support.</div><a id="template-i6c2y" name="link_template-i6c2y"
                        Info@10decoders.com</a>

                        <div id="template-i433j" class="">For More Info.</div>
                    </div>
                </div>
        </div>
        <div id="template-i3a4" class="gjs-cell">
            <div id="template-ir5f4" class="">Login</div>
            <input id="template-i7h1i" placeholder="Your Email or Phone Number"
            class="input form-control " />
            <input id="template-ioido" placeholder="Password" class="input form-control "
            />
            <div id="template-i9mea" class="gjs-row">
                <div id="template-ii091" class="gjs-cell">
                    <div type="checkbox" id="template-ia9di" class="checkbox form-control "></div>
                    <div id="template-ibsp9" class="">Remember me</div>
                </div>
                <div id="template-ib1qk" class="gjs-cell">
                    <div id="template-ixu0e" class="">Forgot Password</div>
                </div>
            </div>
            <div id="template-io2af" class="gjs-row">
                <div id="template-itchi" class="gjs-cell">
                    <div id="template-irlwj" class="button btn btn-primary ">Login</div>
                </div>
                <div id="template-ish4c" class="gjs-cell">
                    <div id="template-iqltn" class="button btn btn-primary ">Sign Up
                        <br id="template-iu5z8" class="">
                    </div>
                    <div id="template-iq5o5" class="gjs-row">
                        <div id="template-iiqxh" class="gjs-cell">
                            <img id="template-iv7wh" src="https://grapesjs-images.s3.amazonaws.com/grapesjsimages/or.png"
                            </div>
                        </div>
                    </div>
                </div>
                <div id="template-i6wik" class="gjs-row">
                    <div id="template-iylo1" class="gjs-cell">
                        <img id="template-igpg3" src="https://grapesjs-images.s3.amazonaws.com/grapesjsimages/Image%2018.png"
                        <div id="template-icpnj" class="">Sign In With Google</div>
                </div>
            </div>
        </div>
    </div>

// application/client/web/templateaccouting/src/app/loginsscreen/loginsscreen.tsx
import React from 'react';
import { AgGridReact } from 'ag-grid-react';
import {Link} from 'react-router-dom';
import {Upload} from "../../shared/shared.service";
import Select from "react-select";
import "./loginsscreen.scss";
import  {service}   from './loginsscreen.service';

class Loginsscreen extends React.Component<any, any> {
    test = new service ("");
    constructor(props:any){
    super(props);
    this.state={
    adds : {
    name: '',
    },
    
    rowData :[]
    } }


    handlechange = (e: any) => {
    if(e?.target){
    this.setState({ adds: { ...this.state.adds, [e.target.name]: e.target.value } })
    }
    }


    componentDidMount() {
    this.state.adds.created_by = sessionStorage.getItem('email')||'{}';
    }

    render(){
    return(
    <>
        <h2 className="screen-align">loginsscreen</h2>
        <div id="template-isvn" className="gjs-row">
    <div id="template-iwqv" className="gjs-cell">
        <div id="template-ix5t6" className="gjs-row">
            <div id="template-ix4oh" className="gjs-cell"></div>
        </div>
        <div id="template-ictg">The GST Council Has Made E-Invoicing Mandatory for Businesses with a Turnover
            Of ₹10Cr. Or More From October 2023. 10Decoders Books Is Here To Help.</div>
        <div
        id="template-ihzr" className="gjs-row">
            <div id="template-ijc9" className="gjs-cell"></div>
    </div>
    <div id="template-ihxdj" className="gjs-row">
        <div id="template-iomak" className="gjs-cell">
            <div id="template-iz9hl">Reach Out To Support.</div>
            <div id="template-i433j">For More Info.</div>
        </div>
    </div>
</div>
<div id="template-i3a4" className="gjs-cell">
    <div id="template-ir5f4">Login</div>
    <input id="template-i7h1i" placeholder="Your Email or Phone Number"
    className="input form-control " />
    <input id="template-ioido" placeholder="Password" className="input form-control "
    />
    <div id="template-i9mea" className="gjs-row">
        <div id="template-ii091" className="gjs-cell">
            <input type="checkbox" id="template-ia9di" className="checkbox form-control "
            />
            <div id="template-ibsp9">Remember me</div>
        </div>
        <div id="template-ib1qk" className="gjs-cell">
            <div id="template-ixu0e">Forgot Password</div>
        </div>
    </div>
    <div id="template-io2af" className="gjs-row">
        <div id="template-itchi" className="gjs-cell">
            <button id="template-irlwj" className="button btn btn-primary ">Login</button>
        </div>
        <div id="template-ish4c" className="gjs-cell">
            <button id="template-iqltn" className="button btn btn-primary ">Sign Up
                <br id="template-iu5z8"></br>
            </button>
            <div id="template-iq5o5" className="gjs-row">
                <div id="template-iiqxh" className="gjs-cell"></div>
            </div>
        </div>
    </div>
    <div id="template-i6wik" className="gjs-row">
        <div id="template-iylo1" className="gjs-cell">
            <div id="template-icpnj">Sign In With Google</div>
        </div>
    </div>
</div>
</div>
    </>
    );
    };
    };

    export default Loginsscreen;
